<#
.SYNOPSIS
    Evaluates and optionally enables the Use_Notify option on AD Site Links and Replication Connections.

.DESCRIPTION
    This tool analyzes Active Directory replication topology to identify where the Use_Notify
    feature isn't enabled, and can optionally enable it. Generates an HTML dashboard report.

    Use_Notify enables change notification between domain controllers, reducing replication latency
    from the default 15-minute schedule to near-immediate replication.

    Site Link Options (bit flags):
        0x1 (bit 0) - USE_NOTIFY: Enables change notification for the site link

    Replication Connection Options (bit flags):
        0x1 (bit 0) - IS_GENERATED: Connection was auto-generated by KCC
        0x2 (bit 1) - USE_NOTIFY: Enables change notification for the connection

    Registry Settings (HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters):
        - "Replicator notify pause after modify (secs)": Holdback timer before notifying partners (default: 300)
        - "Replicator notify pause between DSAs (secs)": Delay between partner notifications (default: 30)

    Registry Settings (HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters):
        - "AvoidPdcOnWan": When set to 1, DCs won't contact PDC emulator for password changes if in different site

    Reference: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/
    Reference: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc961787(v=technet.10)

.PARAMETER ReportOnly
    Generate a report without making any changes. This is the default behavior.

.PARAMETER EnableSiteLinks
    Enable Use_Notify on site links that don't have it configured.

.PARAMETER EnableReplicationConnections
    Enable Use_Notify on manually-created replication connections that don't have it configured.
    Note: Auto-generated connections inherit behavior from site links.

.PARAMETER GetRegistrySettings
    Query domain controllers for NTDS notification timer registry settings and AvoidPdcOnWan.
    Requires WinRM connectivity to domain controllers.

.PARAMETER ReportPath
    Path to save the HTML report file. Defaults to desktop with timestamp.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1
    Generates an HTML dashboard report of current Use_Notify status.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1 -GetRegistrySettings
    Generates a report including registry notification timer settings from all DCs.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1 -EnableSiteLinks -WhatIf
    Shows what site links would be modified without making changes.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1 -EnableSiteLinks -EnableReplicationConnections
    Enables Use_Notify on both site links and manual replication connections.

.LINK
    https://github.com/Mike-Crowley/Public-Scripts

.NOTES
    Author: Mike Crowley
    Requires: ActiveDirectory module
#>

#Requires -Modules ActiveDirectory

[CmdletBinding(SupportsShouldProcess = $true, DefaultParameterSetName = 'Report')]
param (
    [Parameter(ParameterSetName = 'Report')]
    [switch]$ReportOnly,

    [Parameter(ParameterSetName = 'Enable')]
    [switch]$EnableSiteLinks,

    [Parameter(ParameterSetName = 'Enable')]
    [switch]$EnableReplicationConnections,

    [switch]$GetRegistrySettings,

    [ValidateNotNullOrEmpty()]
    [string]$ReportPath = "$env:USERPROFILE\Desktop\$(Get-Date -Format 'yyyyMMdd_HHmmss')_UseNotifyReport.html"
)

# Bit flag constants - Site Links
$SITELINK_USE_NOTIFY = 0x1          # Bit 0 - Enables change notification for the site link

# Bit flag constants - Replication Connections
$CONN_IS_GENERATED = 0x1            # Bit 0 for connections (auto-generated by KCC)
$CONN_USE_NOTIFY = 0x2              # Bit 1 for connections (use notify)

# Registry default values
$DEFAULT_NOTIFY_PAUSE_AFTER_MODIFY = 300  # seconds (holdback timer)
$DEFAULT_NOTIFY_PAUSE_BETWEEN_DSAS = 30   # seconds (delay between notifications)

#region Helper Functions

function Get-SiteLinkStatus {
    [CmdletBinding()]
    param()

    Get-ADReplicationSiteLink -Filter * -Properties options, Cost, ReplicationFrequencyInMinutes, SitesIncluded | ForEach-Object {
        $options = if ($null -eq $_.options) { 0 } else { [int]$_.options }
        $sites = ($_.SitesIncluded | ForEach-Object { ($_ -split ',')[0] -replace 'CN=', '' }) -join ', '
        [PSCustomObject]@{
            Name                          = $_.Name
            DistinguishedName             = $_.DistinguishedName
            Cost                          = $_.Cost
            ReplicationFrequencyInMinutes = $_.ReplicationFrequencyInMinutes
            SitesIncluded                 = $sites
            Options                       = $options
            OptionsHex                    = '0x{0:X}' -f $options
            NotifyEnabled                 = ($options -band $SITELINK_USE_NOTIFY) -eq $SITELINK_USE_NOTIFY
        }
    }
}

function Get-ReplicationConnectionStatus {
    [CmdletBinding()]
    param()

    Get-ADReplicationConnection -Filter * -Properties options | ForEach-Object {
        $options = if ($null -eq $_.options) { 0 } else { [int]$_.options }
        $isGenerated = ($options -band $CONN_IS_GENERATED) -eq $CONN_IS_GENERATED
        $notifyEnabled = ($options -band $CONN_USE_NOTIFY) -eq $CONN_USE_NOTIFY

        [PSCustomObject]@{
            Name              = $_.Name
            FromServer        = ($_.ReplicateFromDirectoryServer -split ',')[1] -replace 'CN=', ''
            ToServer          = ($_.ReplicateToDirectoryServer -split ',')[0] -replace 'CN=', ''
            ParentSite        = ($_.DistinguishedName -split ',')[4] -replace 'CN=', ''
            DistinguishedName = $_.DistinguishedName
            Options           = $options
            OptionsHex        = '0x{0:X}' -f $options
            AutoGenerated     = $isGenerated
            NotifyEnabled     = $notifyEnabled
            NeedsChange       = (-not $isGenerated) -and (-not $notifyEnabled)
        }
    }
}

function Get-DCRegistrySettings {
    [CmdletBinding()]
    param()

    $DomainDN = (Get-ADDomain).DistinguishedName
    $DCs = Get-ADComputer -Filter * -SearchBase "OU=Domain Controllers,$DomainDN" -Properties DNSHostName

    foreach ($DC in $DCs) {
        $result = [PSCustomObject]@{
            ComputerName                = $DC.Name
            DNSHostName                 = $DC.DNSHostName
            NotifyPauseAfterModify      = $null
            NotifyPauseAfterModify_Note = $null
            NotifyPauseBetweenDSAs      = $null
            NotifyPauseBetweenDSAs_Note = $null
            AvoidPdcOnWan               = $null
            AvoidPdcOnWan_Note          = $null
            Error                       = $null
        }

        try {
            $ntdsParams = Invoke-Command -ComputerName $DC.DNSHostName -ScriptBlock {
                Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters' -ErrorAction SilentlyContinue
            } -ErrorAction Stop

            $netlogonParams = Invoke-Command -ComputerName $DC.DNSHostName -ScriptBlock {
                Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -ErrorAction SilentlyContinue
            } -ErrorAction Stop

            # Notification pause after modify (holdback timer)
            $pauseAfterModify = $ntdsParams.'Replicator notify pause after modify (secs)'
            if ($null -eq $pauseAfterModify) {
                $result.NotifyPauseAfterModify = $DEFAULT_NOTIFY_PAUSE_AFTER_MODIFY
                $result.NotifyPauseAfterModify_Note = 'default'
            }
            else {
                $result.NotifyPauseAfterModify = $pauseAfterModify
                $result.NotifyPauseAfterModify_Note = 'custom'
            }

            # Notification pause between DSAs
            $pauseBetweenDSAs = $ntdsParams.'Replicator notify pause between DSAs (secs)'
            if ($null -eq $pauseBetweenDSAs) {
                $result.NotifyPauseBetweenDSAs = $DEFAULT_NOTIFY_PAUSE_BETWEEN_DSAS
                $result.NotifyPauseBetweenDSAs_Note = 'default'
            }
            else {
                $result.NotifyPauseBetweenDSAs = $pauseBetweenDSAs
                $result.NotifyPauseBetweenDSAs_Note = 'custom'
            }

            # AvoidPdcOnWan setting
            $avoidPdc = $netlogonParams.AvoidPdcOnWan
            if ($null -eq $avoidPdc) {
                $result.AvoidPdcOnWan = 0
                $result.AvoidPdcOnWan_Note = 'default'
            }
            elseif ($avoidPdc -eq 1) {
                $result.AvoidPdcOnWan = 1
                $result.AvoidPdcOnWan_Note = 'enabled'
            }
            else {
                $result.AvoidPdcOnWan = $avoidPdc
                $result.AvoidPdcOnWan_Note = 'custom'
            }
        }
        catch {
            $result.Error = $_.Exception.Message
        }

        $result
    }
}

#endregion

#region Main Logic

# Get forest/domain info
$Forest = Get-ADForest
$Domain = Get-ADDomain

Write-Verbose "Retrieving site link information..."
$SiteLinks = Get-SiteLinkStatus

Write-Verbose "Retrieving replication connection information..."
$ReplicationConnections = Get-ReplicationConnectionStatus

# Get AD Sites
$Sites = Get-ADReplicationSite -Filter *

# Registry settings (optional)
$RegistrySettings = $null
if ($GetRegistrySettings) {
    Write-Verbose "Retrieving DC registry settings (requires WinRM)..."
    $RegistrySettings = Get-DCRegistrySettings
}

$SiteLinksEnabled = $SiteLinks | Where-Object { $_.NotifyEnabled }
$SiteLinksDisabled = $SiteLinks | Where-Object { -not $_.NotifyEnabled }
$ConnectionsOK = $ReplicationConnections | Where-Object { -not $_.NeedsChange }
$ConnectionsNeedChange = $ReplicationConnections | Where-Object { $_.NeedsChange }
$ConnectionsAutoGen = $ReplicationConnections | Where-Object { $_.AutoGenerated }
$ConnectionsManual = $ReplicationConnections | Where-Object { -not $_.AutoGenerated }

# Calculate health score
$totalItems = $SiteLinks.Count + $ConnectionsManual.Count
$healthyItems = $SiteLinksEnabled.Count + ($ConnectionsManual | Where-Object { $_.NotifyEnabled }).Count
$healthScore = if ($totalItems -gt 0) { [math]::Round(($healthyItems / $totalItems) * 100) } else { 100 }

# Determine status color
$statusColor = switch ($healthScore) {
    { $_ -eq 100 } { '#4ade80' }  # Green
    { $_ -ge 75 } { '#fbbf24' }   # Yellow
    { $_ -ge 50 } { '#fb923c' }   # Orange
    default { '#f87171' }          # Red
}

# Build HTML report
$htmlContent = @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AD Replication Notify Report - $($Forest.Name)</title>
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0; padding: 20px;
            background: #1a1a2e; color: #eee;
        }
        .container { max-width: 1400px; margin: 0 auto; }
        h1 { color: #00d4ff; margin-bottom: 5px; }
        h2 { color: #00d4ff; margin-top: 40px; margin-bottom: 15px; border-bottom: 1px solid #2a2a4a; padding-bottom: 10px; }
        .subtitle { color: #888; margin-bottom: 30px; font-size: 14px; }
        .header-info {
            background: #16213e; padding: 15px 20px; border-radius: 8px;
            margin-bottom: 30px; border-left: 4px solid #00d4ff;
        }
        .header-info span { margin-right: 30px; }
        .header-info strong { color: #00d4ff; }
        .metrics {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 15px; margin-bottom: 30px;
        }
        .metric {
            background: #16213e; padding: 20px; border-radius: 8px;
            border-left: 4px solid #00d4ff;
        }
        .metric.good { border-left-color: #4ade80; }
        .metric.warning { border-left-color: #fbbf24; }
        .metric.bad { border-left-color: #f87171; }
        .metric-value { font-size: 32px; font-weight: bold; color: #00d4ff; }
        .metric.good .metric-value { color: #4ade80; }
        .metric.warning .metric-value { color: #fbbf24; }
        .metric.bad .metric-value { color: #f87171; }
        .metric-label { color: #888; font-size: 13px; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 14px; }
        th, td { padding: 12px 10px; text-align: left; border-bottom: 1px solid #2a2a4a; }
        th { background: #16213e; color: #00d4ff; font-weight: 600; position: sticky; top: 0; }
        tr:hover { background: #1f1f3a; }
        .status-good { color: #4ade80; font-weight: 600; }
        .status-bad { color: #f87171; font-weight: 600; }
        .status-info { color: #60a5fa; }
        .status-warn { color: #fbbf24; }
        .tag {
            display: inline-block; padding: 3px 8px; border-radius: 4px;
            font-size: 12px; font-weight: 600;
        }
        .tag-green { background: #166534; color: #4ade80; }
        .tag-red { background: #7f1d1d; color: #fca5a5; }
        .tag-blue { background: #1e3a5f; color: #60a5fa; }
        .tag-yellow { background: #713f12; color: #fbbf24; }
        .tag-gray { background: #374151; color: #9ca3af; }
        .info-box {
            background: #1e3a5f; border-left: 4px solid #60a5fa;
            padding: 15px 20px; border-radius: 0 8px 8px 0; margin: 20px 0;
        }
        .info-box h4 { color: #60a5fa; margin: 0 0 10px 0; }
        .info-box p { margin: 5px 0; color: #cbd5e1; font-size: 14px; }
        .info-box code { background: #0f172a; padding: 2px 6px; border-radius: 3px; font-size: 13px; }
        .recommendation {
            background: #14532d; border-left: 4px solid #4ade80;
            padding: 15px 20px; border-radius: 0 8px 8px 0; margin: 20px 0;
        }
        .recommendation.warning {
            background: #713f12; border-left-color: #fbbf24;
        }
        .recommendation h4 { color: #4ade80; margin: 0 0 10px 0; }
        .recommendation.warning h4 { color: #fbbf24; }
        .recommendation p { margin: 5px 0; color: #cbd5e1; font-size: 14px; }
        .section-desc { color: #888; font-size: 14px; margin-bottom: 15px; }
        .truncate { max-width: 250px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
        .mono { font-family: 'Consolas', 'Monaco', monospace; font-size: 13px; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #2a2a4a; color: #666; font-size: 12px; }
        .collapsible { cursor: pointer; user-select: none; }
        .collapsible:hover { color: #00d4ff; }
        .collapsible::before { content: '▼ '; font-size: 10px; }
        .collapsible.collapsed::before { content: '▶ '; }
        .content { display: block; }
        .content.hidden { display: none; }
    </style>
</head>
<body>
    <div class="container">
        <h1>AD Replication Notify Report</h1>
        <p class="subtitle">Use_Notify configuration analysis for change notification replication</p>

        <div class="header-info">
            <span><strong>Forest:</strong> $($Forest.Name)</span>
            <span><strong>Domain:</strong> $($Domain.DNSRoot)</span>
            <span><strong>Forest Mode:</strong> $($Forest.ForestMode)</span>
            <span><strong>Generated:</strong> $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</span>
        </div>

        <div class="metrics">
            <div class="metric $(if ($healthScore -eq 100) { 'good' } elseif ($healthScore -ge 75) { 'warning' } else { 'bad' })">
                <div class="metric-value">$healthScore%</div>
                <div class="metric-label">Health Score</div>
            </div>
            <div class="metric">
                <div class="metric-value">$($Sites.Count)</div>
                <div class="metric-label">AD Sites</div>
            </div>
            <div class="metric $(if ($SiteLinksDisabled.Count -eq 0) { 'good' } else { 'bad' })">
                <div class="metric-value">$($SiteLinksEnabled.Count)/$($SiteLinks.Count)</div>
                <div class="metric-label">Site Links with Notify</div>
            </div>
            <div class="metric">
                <div class="metric-value">$($ReplicationConnections.Count)</div>
                <div class="metric-label">Replication Connections</div>
            </div>
            <div class="metric $(if ($ConnectionsNeedChange.Count -eq 0) { 'good' } elseif ($ConnectionsNeedChange.Count -le 2) { 'warning' } else { 'bad' })">
                <div class="metric-value">$($ConnectionsNeedChange.Count)</div>
                <div class="metric-label">Connections Need Attention</div>
            </div>
$(if ($RegistrySettings) {
    $dcsQueried = ($RegistrySettings | Where-Object { $null -eq $_.Error }).Count
    $dcsWithErrors = ($RegistrySettings | Where-Object { $null -ne $_.Error }).Count
    "            <div class='metric $(if ($dcsWithErrors -eq 0) { 'good' } else { 'warning' })'>" +
    "                <div class='metric-value'>$dcsQueried/$($RegistrySettings.Count)</div>" +
    "                <div class='metric-label'>DCs Registry Queried</div>" +
    "            </div>"
})
        </div>

$(if ($SiteLinksDisabled.Count -gt 0) {
@"
        <div class="recommendation warning">
            <h4>Action Recommended</h4>
            <p><strong>$($SiteLinksDisabled.Count) site link(s)</strong> do not have Use_Notify enabled. Without change notification,
            replication between sites follows the schedule interval (typically 15-180 minutes) rather than occurring immediately after changes.</p>
            <p>Run with <code>-EnableSiteLinks</code> to enable Use_Notify on these site links.</p>
        </div>
"@
} else {
@"
        <div class="recommendation">
            <h4>All Site Links Configured</h4>
            <p>All site links have Use_Notify enabled. Changes will replicate between sites via change notification rather than waiting for scheduled intervals.</p>
        </div>
"@
})

        <h2>Site Links</h2>
        <p class="section-desc">
            Site links define replication topology between AD sites. When Use_Notify (0x1) is enabled,
            domain controllers send change notifications across the link, enabling near-immediate replication instead of waiting for the scheduled interval.
        </p>

        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Schedule (min)</th>
                    <th>Sites Included</th>
                    <th>Use_Notify</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
$(foreach ($link in ($SiteLinks | Sort-Object Name)) {
    $notifyClass = if ($link.NotifyEnabled) { 'tag-green' } else { 'tag-red' }
    $notifyText = if ($link.NotifyEnabled) { 'Enabled' } else { 'Disabled' }
@"
                <tr>
                    <td><strong>$($link.Name)</strong></td>
                    <td>$($link.Cost)</td>
                    <td>$($link.ReplicationFrequencyInMinutes)</td>
                    <td class="truncate" title="$($link.SitesIncluded)">$($link.SitesIncluded)</td>
                    <td><span class="tag $notifyClass">$notifyText</span></td>
                    <td class="mono">$($link.OptionsHex)</td>
                </tr>
"@
})
            </tbody>
        </table>

        <h2>Replication Connections</h2>
        <p class="section-desc">
            Replication connections define the inbound replication path for each domain controller.
            <strong>Auto-generated</strong> connections (created by KCC) inherit Use_Notify from site links.
            <strong>Manual</strong> connections require Use_Notify (0x2) to be set explicitly.
        </p>

        <div class="info-box">
            <h4>Understanding Connection Types</h4>
            <p><strong>Auto-Generated (KCC):</strong> Created automatically by the Knowledge Consistency Checker. These inherit notification behavior from site links - no manual configuration needed.</p>
            <p><strong>Manual:</strong> Administrator-created connections. Must have Use_Notify bit (0x2) set explicitly for change notification to work.</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>From Server</th>
                    <th>To Server</th>
                    <th>Site</th>
                    <th>Type</th>
                    <th>Use_Notify</th>
                    <th>Status</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
$(foreach ($conn in ($ReplicationConnections | Sort-Object ParentSite, ToServer)) {
    $typeClass = if ($conn.AutoGenerated) { 'tag-blue' } else { 'tag-yellow' }
    $typeText = if ($conn.AutoGenerated) { 'Auto (KCC)' } else { 'Manual' }
    $notifyClass = if ($conn.NotifyEnabled) { 'status-good' } else { 'status-info' }
    $notifyText = if ($conn.NotifyEnabled) { 'Yes' } else { 'No' }

    if ($conn.NeedsChange) {
        $statusClass = 'tag-red'
        $statusText = 'Needs Attention'
    } elseif ($conn.AutoGenerated) {
        $statusClass = 'tag-green'
        $statusText = 'OK (Inherits)'
    } else {
        $statusClass = 'tag-green'
        $statusText = 'OK'
    }
@"
                <tr>
                    <td>$($conn.FromServer)</td>
                    <td><strong>$($conn.ToServer)</strong></td>
                    <td>$($conn.ParentSite)</td>
                    <td><span class="tag $typeClass">$typeText</span></td>
                    <td class="$notifyClass">$notifyText</td>
                    <td><span class="tag $statusClass">$statusText</span></td>
                    <td class="mono">$($conn.OptionsHex)</td>
                </tr>
"@
})
            </tbody>
        </table>

$(if ($GetRegistrySettings -and $RegistrySettings) {
    $DCsWithSettings = $RegistrySettings | Where-Object { $null -eq $_.Error }
    $DCsWithErrors = $RegistrySettings | Where-Object { $null -ne $_.Error }
@"
        <h2>Domain Controller Registry Settings</h2>
        <p class="section-desc">
            These registry settings control notification timing behavior on each domain controller.
            Values shown are effective settings (custom values or defaults).
        </p>

        <div class="info-box">
            <h4>Registry Settings Reference</h4>
            <p><strong>Notify Pause After Modify (Holdback):</strong> Time to wait after a change before notifying partners. Default: 300 seconds (5 min).
            Prevents excessive notifications during bulk changes.</p>
            <p><strong>Notify Pause Between DSAs:</strong> Delay between notifying each replication partner. Default: 30 seconds.
            Spreads out replication load across partners.</p>
            <p><strong>AvoidPdcOnWan:</strong> When enabled (1), DCs won't urgently replicate password changes to PDC emulator if it's in a different site.
            Useful for branch offices with unreliable WAN links.</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Domain Controller</th>
                    <th>Holdback Timer</th>
                    <th>Inter-DSA Delay</th>
                    <th>AvoidPdcOnWan</th>
                </tr>
            </thead>
            <tbody>
$(foreach ($dc in ($DCsWithSettings | Sort-Object ComputerName)) {
    $holdbackClass = if ($dc.NotifyPauseAfterModify_Note -eq 'custom') { 'status-warn' } else { '' }
    $dsaClass = if ($dc.NotifyPauseBetweenDSAs_Note -eq 'custom') { 'status-warn' } else { '' }
    $pdcClass = if ($dc.AvoidPdcOnWan -eq 1) { 'status-warn' } else { '' }
    $pdcText = if ($dc.AvoidPdcOnWan -eq 1) { 'Enabled' } else { 'Disabled' }
@"
                <tr>
                    <td><strong>$($dc.ComputerName)</strong></td>
                    <td class="$holdbackClass">$($dc.NotifyPauseAfterModify)s <span class="tag tag-gray">$($dc.NotifyPauseAfterModify_Note)</span></td>
                    <td class="$dsaClass">$($dc.NotifyPauseBetweenDSAs)s <span class="tag tag-gray">$($dc.NotifyPauseBetweenDSAs_Note)</span></td>
                    <td class="$pdcClass">$pdcText <span class="tag tag-gray">$($dc.AvoidPdcOnWan_Note)</span></td>
                </tr>
"@
})
$(if ($DCsWithErrors) {
    foreach ($dc in $DCsWithErrors) {
@"
                <tr>
                    <td><strong>$($dc.ComputerName)</strong></td>
                    <td colspan="3" class="status-bad">Connection Error: $($dc.Error)</td>
                </tr>
"@
    }
})
            </tbody>
        </table>
"@
})

        <h2>Reference</h2>
        <div class="info-box">
            <h4>Site Link Options Bit Flags</h4>
            <p><code>0x1</code> (bit 0) - <strong>USE_NOTIFY:</strong> Enables change notification. DCs will notify partners of changes rather than waiting for scheduled replication.</p>
        </div>
        <div class="info-box">
            <h4>Replication Connection Options Bit Flags</h4>
            <p><code>0x1</code> (bit 0) - <strong>IS_GENERATED:</strong> Connection was auto-generated by KCC. These connections inherit notification settings from site links.</p>
            <p><code>0x2</code> (bit 1) - <strong>USE_NOTIFY:</strong> For manual connections, enables change notification. Has no effect on KCC-generated connections.</p>
        </div>

        <div class="footer">
            <p>Generated by <a href="https://github.com/Mike-Crowley/Public-Scripts" style="color: #00d4ff;">Update-UseNotifyReplication.ps1</a> |
            Author: Mike Crowley |
            <a href="https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc961787(v=technet.10)" style="color: #888;">Microsoft Docs Reference</a></p>
        </div>
    </div>

    <script>
        document.querySelectorAll('.collapsible').forEach(el => {
            el.addEventListener('click', () => {
                el.classList.toggle('collapsed');
                el.nextElementSibling.classList.toggle('hidden');
            });
        });
    </script>
</body>
</html>
"@

# Save HTML report
try {
    $htmlContent | Out-File -FilePath $ReportPath -Encoding UTF8 -Force
    Write-Host "Report saved to: $ReportPath" -ForegroundColor Green

    # Open the report
    Start-Process $ReportPath
}
catch {
    Write-Error "Failed to save report: $_"
}

#endregion

#region Enable Mode

if ($EnableSiteLinks -or $EnableReplicationConnections) {

    # Create backup before making changes
    $BackupPath = $ReportPath -replace '\.html$', '_Backup.txt'
    $BackupData = @()
    $BackupData += "BACKUP CREATED: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $BackupData += "Forest: $($Forest.Name)"
    $BackupData += "Domain: $($Domain.DNSRoot)"
    $BackupData += ""

    if ($EnableSiteLinks -and $SiteLinksDisabled) {
        $BackupData += "SITE LINKS (before changes):"
        $BackupData += ($SiteLinksDisabled | Select-Object Name, DistinguishedName, Options, OptionsHex | Format-List | Out-String)

        foreach ($SiteLink in $SiteLinksDisabled) {
            $newOptions = $SiteLink.Options -bor $SITELINK_USE_NOTIFY
            if ($PSCmdlet.ShouldProcess($SiteLink.Name, "Set options from 0x$($SiteLink.Options.ToString('X')) to 0x$($newOptions.ToString('X'))")) {
                try {
                    Set-ADReplicationSiteLink -Identity $SiteLink.DistinguishedName -Replace @{'options' = $newOptions }
                    Write-Host "  Updated site link: $($SiteLink.Name)" -ForegroundColor Cyan
                }
                catch {
                    Write-Error "Failed to update site link $($SiteLink.Name): $_"
                }
            }
        }
    }

    if ($EnableReplicationConnections -and $ConnectionsNeedChange) {
        $BackupData += "REPLICATION CONNECTIONS (before changes):"
        $BackupData += ($ConnectionsNeedChange | Select-Object Name, DistinguishedName, Options, OptionsHex | Format-List | Out-String)

        foreach ($Connection in $ConnectionsNeedChange) {
            $newOptions = $Connection.Options -bor $CONN_USE_NOTIFY
            if ($PSCmdlet.ShouldProcess($Connection.Name, "Set options from 0x$($Connection.Options.ToString('X')) to 0x$($newOptions.ToString('X'))")) {
                try {
                    Set-ADReplicationConnection -Identity $Connection.DistinguishedName -Replace @{'options' = $newOptions }
                    Write-Host "  Updated connection: $($Connection.Name)" -ForegroundColor Cyan
                }
                catch {
                    Write-Error "Failed to update connection $($Connection.Name): $_"
                }
            }
        }
    }

    # Save backup
    if ($BackupData.Count -gt 4) {
        $BackupData | Out-File -FilePath $BackupPath -Encoding UTF8 -Force
        Write-Host "Backup saved to: $BackupPath" -ForegroundColor Yellow
    }
}

#endregion
