<#
.SYNOPSIS
    Evaluates and optionally enables the Use_Notify option on AD Site Links and Replication Connections.

.DESCRIPTION
    This tool analyzes Active Directory replication topology to identify where the Use_Notify
    feature isn't enabled, and can optionally enable it.

    Use_Notify enables change notification between domain controllers, reducing replication latency
    from the default 15-minute schedule to near-immediate replication.

    Site Link Options (bit flags):
        0x1 (bit 0) - USE_NOTIFY: Enables change notification for the site link

    Replication Connection Options (bit flags):
        0x1 (bit 0) - IS_GENERATED: Connection was auto-generated by KCC
        0x2 (bit 1) - USE_NOTIFY: Enables change notification for the connection

    Registry Settings (HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters):
        - "Replicator notify pause after modify (secs)": Holdback timer before notifying partners (default: 300)
        - "Replicator notify pause between DSAs (secs)": Delay between partner notifications (default: 30)

    Registry Settings (HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters):
        - "AvoidPdcOnWan": When set to 1, DCs won't contact PDC emulator for password changes if in different site

    Reference: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/
    Reference: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc961787(v=technet.10)

.PARAMETER ReportOnly
    Generate a report without making any changes. This is the default behavior.

.PARAMETER EnableSiteLinks
    Enable Use_Notify on site links that don't have it configured.

.PARAMETER EnableReplicationConnections
    Enable Use_Notify on manually-created replication connections that don't have it configured.
    Note: Auto-generated connections inherit behavior from site links.

.PARAMETER GetRegistrySettings
    Query domain controllers for NTDS notification timer registry settings and AvoidPdcOnWan.
    Requires WinRM connectivity to domain controllers.

.PARAMETER ReportPath
    Path to save the report file. Defaults to desktop.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1
    Generates a report of current Use_Notify status without making changes.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1 -GetRegistrySettings
    Generates a report including registry notification timer settings from all DCs.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1 -EnableSiteLinks -WhatIf
    Shows what site links would be modified without making changes.

.EXAMPLE
    .\Update-UseNotifyReplication.ps1 -EnableSiteLinks -EnableReplicationConnections
    Enables Use_Notify on both site links and manual replication connections.

.LINK
    https://github.com/Mike-Crowley/Public-Scripts

.NOTES
    Author: Mike Crowley
    Requires: ActiveDirectory module
#>

#Requires -Modules ActiveDirectory

[CmdletBinding(SupportsShouldProcess = $true, DefaultParameterSetName = 'Report')]
param (
    [Parameter(ParameterSetName = 'Report')]
    [switch]$ReportOnly,

    [Parameter(ParameterSetName = 'Enable')]
    [switch]$EnableSiteLinks,

    [Parameter(ParameterSetName = 'Enable')]
    [switch]$EnableReplicationConnections,

    [switch]$GetRegistrySettings,

    [ValidateNotNullOrEmpty()]
    [string]$ReportPath = "$env:USERPROFILE\Desktop\$(Get-Date -Format 'yyyyMMdd_HHmmss')_UseNotifyReport.txt"
)

# Bit flag constants - Site Links
$SITELINK_USE_NOTIFY = 0x1          # Bit 0 - Enables change notification for the site link

# Bit flag constants - Replication Connections
$CONN_IS_GENERATED = 0x1            # Bit 0 for connections (auto-generated by KCC)
$CONN_USE_NOTIFY = 0x2              # Bit 1 for connections (use notify)

# Registry default values
$DEFAULT_NOTIFY_PAUSE_AFTER_MODIFY = 300  # seconds (holdback timer)
$DEFAULT_NOTIFY_PAUSE_BETWEEN_DSAS = 30   # seconds (delay between notifications)

#region Helper Functions

function Get-SiteLinkStatus {
    [CmdletBinding()]
    param()

    Get-ADReplicationSiteLink -Filter * -Properties options, Cost, ReplicationFrequencyInMinutes, SitesIncluded | ForEach-Object {
        $options = if ($null -eq $_.options) { 0 } else { [int]$_.options }
        $sites = ($_.SitesIncluded | ForEach-Object { ($_ -split ',')[0] -replace 'CN=', '' }) -join ', '
        [PSCustomObject]@{
            Name                          = $_.Name
            DistinguishedName             = $_.DistinguishedName
            Cost                          = $_.Cost
            ReplicationFrequencyInMinutes = $_.ReplicationFrequencyInMinutes
            SitesIncluded                 = $sites
            Options                       = $options
            OptionsHex                    = '0x{0:X}' -f $options
            NotifyEnabled                 = ($options -band $SITELINK_USE_NOTIFY) -eq $SITELINK_USE_NOTIFY
        }
    }
}

function Get-ReplicationConnectionStatus {
    [CmdletBinding()]
    param()

    Get-ADReplicationConnection -Filter * -Properties options | ForEach-Object {
        $options = if ($null -eq $_.options) { 0 } else { [int]$_.options }
        $isGenerated = ($options -band $CONN_IS_GENERATED) -eq $CONN_IS_GENERATED
        $notifyEnabled = ($options -band $CONN_USE_NOTIFY) -eq $CONN_USE_NOTIFY

        [PSCustomObject]@{
            Name              = $_.Name
            FromServer        = ($_.ReplicateFromDirectoryServer -split ',')[1] -replace 'CN=', ''
            ToServer          = ($_.ReplicateToDirectoryServer -split ',')[0] -replace 'CN=', ''
            ParentSite        = ($_.DistinguishedName -split ',')[4] -replace 'CN=', ''
            DistinguishedName = $_.DistinguishedName
            Options           = $options
            OptionsHex        = '0x{0:X}' -f $options
            AutoGenerated     = $isGenerated
            NotifyEnabled     = $notifyEnabled
            NeedsChange       = (-not $isGenerated) -and (-not $notifyEnabled)
        }
    }
}

function Get-DCRegistrySettings {
    [CmdletBinding()]
    param()

    $DomainDN = (Get-ADDomain).DistinguishedName
    $DCs = Get-ADComputer -Filter * -SearchBase "OU=Domain Controllers,$DomainDN" -Properties DNSHostName

    foreach ($DC in $DCs) {
        $result = [PSCustomObject]@{
            ComputerName                = $DC.Name
            DNSHostName                 = $DC.DNSHostName
            NotifyPauseAfterModify      = $null
            NotifyPauseAfterModify_Note = $null
            NotifyPauseBetweenDSAs      = $null
            NotifyPauseBetweenDSAs_Note = $null
            AvoidPdcOnWan               = $null
            AvoidPdcOnWan_Note          = $null
            Error                       = $null
        }

        try {
            $ntdsParams = Invoke-Command -ComputerName $DC.DNSHostName -ScriptBlock {
                Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters' -ErrorAction SilentlyContinue
            } -ErrorAction Stop

            $netlogonParams = Invoke-Command -ComputerName $DC.DNSHostName -ScriptBlock {
                Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters' -ErrorAction SilentlyContinue
            } -ErrorAction Stop

            # Notification pause after modify (holdback timer)
            $pauseAfterModify = $ntdsParams.'Replicator notify pause after modify (secs)'
            if ($null -eq $pauseAfterModify) {
                $result.NotifyPauseAfterModify = $DEFAULT_NOTIFY_PAUSE_AFTER_MODIFY
                $result.NotifyPauseAfterModify_Note = '(default)'
            }
            else {
                $result.NotifyPauseAfterModify = $pauseAfterModify
                $result.NotifyPauseAfterModify_Note = '(custom)'
            }

            # Notification pause between DSAs
            $pauseBetweenDSAs = $ntdsParams.'Replicator notify pause between DSAs (secs)'
            if ($null -eq $pauseBetweenDSAs) {
                $result.NotifyPauseBetweenDSAs = $DEFAULT_NOTIFY_PAUSE_BETWEEN_DSAS
                $result.NotifyPauseBetweenDSAs_Note = '(default)'
            }
            else {
                $result.NotifyPauseBetweenDSAs = $pauseBetweenDSAs
                $result.NotifyPauseBetweenDSAs_Note = '(custom)'
            }

            # AvoidPdcOnWan setting
            $avoidPdc = $netlogonParams.AvoidPdcOnWan
            if ($null -eq $avoidPdc) {
                $result.AvoidPdcOnWan = 0
                $result.AvoidPdcOnWan_Note = '(default - will contact PDC)'
            }
            elseif ($avoidPdc -eq 1) {
                $result.AvoidPdcOnWan = 1
                $result.AvoidPdcOnWan_Note = '(enabled - avoids PDC over WAN)'
            }
            else {
                $result.AvoidPdcOnWan = $avoidPdc
                $result.AvoidPdcOnWan_Note = '(custom)'
            }
        }
        catch {
            $result.Error = $_.Exception.Message
        }

        $result
    }
}

#endregion

#region Main Logic

Write-Verbose "Retrieving site link information..."
$SiteLinks = Get-SiteLinkStatus

Write-Verbose "Retrieving replication connection information..."
$ReplicationConnections = Get-ReplicationConnectionStatus

# Registry settings (optional)
$RegistrySettings = $null
if ($GetRegistrySettings) {
    Write-Verbose "Retrieving DC registry settings (requires WinRM)..."
    $RegistrySettings = Get-DCRegistrySettings
}

$SiteLinksEnabled = $SiteLinks | Where-Object { $_.NotifyEnabled }
$SiteLinksDisabled = $SiteLinks | Where-Object { -not $_.NotifyEnabled }
$ConnectionsOK = $ReplicationConnections | Where-Object { -not $_.NeedsChange }
$ConnectionsNeedChange = $ReplicationConnections | Where-Object { $_.NeedsChange }

# Build report
$Report = @()
$Report += "=" * 80
$Report += "USE_NOTIFY REPLICATION REPORT"
$Report += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$Report += "=" * 80
$Report += ""
$Report += "SITE LINKS"
$Report += "-" * 40
$Report += ""
$Report += "All Site Links (with properties):"
if ($SiteLinks) {
    $Report += ($SiteLinks | Select-Object Name, Cost, ReplicationFrequencyInMinutes, NotifyEnabled, OptionsHex, SitesIncluded | Format-Table -AutoSize | Out-String).Trim()
}
$Report += ""
$Report += "$($SiteLinksEnabled.Count) site link(s) have Use_Notify ENABLED (bit 0 = 0x1)"
$Report += "$($SiteLinksDisabled.Count) site link(s) do NOT have Use_Notify enabled"
$Report += ""
if ($SiteLinksDisabled) {
    $Report += "Site links needing Use_Notify:"
    $Report += ($SiteLinksDisabled | Select-Object Name, OptionsHex, DistinguishedName | Format-Table -AutoSize | Out-String).Trim()
    $Report += ""
}
$Report += "REPLICATION CONNECTIONS"
$Report += "-" * 40
$Report += "Note: Auto-generated connections (bit 0 = 0x1) inherit Use_Notify from site links."
$Report += "      Manual connections need Use_Notify explicitly set (bit 1 = 0x2)."
$Report += ""
$Report += "$($ConnectionsOK.Count) connection(s) are OK (auto-generated or already have Use_Notify):"
if ($ConnectionsOK) {
    $Report += ($ConnectionsOK | Select-Object Name, FromServer, ToServer, ParentSite, AutoGenerated, NotifyEnabled, OptionsHex | Format-Table -AutoSize | Out-String).Trim()
}
$Report += ""
$Report += "$($ConnectionsNeedChange.Count) manual connection(s) need Use_Notify enabled:"
if ($ConnectionsNeedChange) {
    $Report += ($ConnectionsNeedChange | Select-Object Name, FromServer, ToServer, ParentSite, OptionsHex, DistinguishedName | Format-Table -AutoSize | Out-String).Trim()
}

# Registry settings section
if ($GetRegistrySettings -and $RegistrySettings) {
    $Report += ""
    $Report += "=" * 80
    $Report += "DOMAIN CONTROLLER REGISTRY SETTINGS"
    $Report += "=" * 80
    $Report += ""
    $Report += "Notification Timer Settings (HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters):"
    $Report += "  - 'Replicator notify pause after modify (secs)': Holdback timer (default: 300 sec)"
    $Report += "  - 'Replicator notify pause between DSAs (secs)': Delay between notifications (default: 30 sec)"
    $Report += ""
    $Report += "Password Replication Setting (HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters):"
    $Report += "  - 'AvoidPdcOnWan': When 1, DC won't contact PDC emulator for password changes if in different site"
    $Report += ""

    $DCsWithSettings = $RegistrySettings | Where-Object { $null -eq $_.Error }
    $DCsWithErrors = $RegistrySettings | Where-Object { $null -ne $_.Error }

    if ($DCsWithSettings) {
        $Report += "Domain Controller Settings:"
        $Report += ($DCsWithSettings | Select-Object ComputerName,
            @{N = 'NotifyAfterModify'; E = { "$($_.NotifyPauseAfterModify)s $($_.NotifyPauseAfterModify_Note)" } },
            @{N = 'NotifyBetweenDSAs'; E = { "$($_.NotifyPauseBetweenDSAs)s $($_.NotifyPauseBetweenDSAs_Note)" } },
            @{N = 'AvoidPdcOnWan'; E = { "$($_.AvoidPdcOnWan) $($_.AvoidPdcOnWan_Note)" } } |
            Format-Table -AutoSize | Out-String).Trim()
    }

    if ($DCsWithErrors) {
        $Report += ""
        $Report += "Domain Controllers with connection errors:"
        $Report += ($DCsWithErrors | Select-Object ComputerName, DNSHostName, Error | Format-Table -AutoSize | Out-String).Trim()
    }
}

# Save report
$Report | Out-File -FilePath $ReportPath -Encoding UTF8 -Force
Write-Host "Report saved to: $ReportPath" -ForegroundColor Green

# If in enable mode, make changes
if ($EnableSiteLinks -or $EnableReplicationConnections) {

    # Create backup before making changes
    $BackupPath = $ReportPath -replace '\.txt$', '_Backup.txt'
    $BackupData = @()
    $BackupData += "BACKUP CREATED: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $BackupData += ""

    if ($EnableSiteLinks -and $SiteLinksDisabled) {
        $BackupData += "SITE LINKS (before changes):"
        $BackupData += ($SiteLinksDisabled | Select-Object Name, DistinguishedName, Options, OptionsHex | Format-List | Out-String)

        foreach ($SiteLink in $SiteLinksDisabled) {
            $newOptions = $SiteLink.Options -bor $SITELINK_USE_NOTIFY
            if ($PSCmdlet.ShouldProcess($SiteLink.Name, "Set options from 0x$($SiteLink.Options.ToString('X')) to 0x$($newOptions.ToString('X'))")) {
                try {
                    Set-ADReplicationSiteLink -Identity $SiteLink.DistinguishedName -Replace @{'options' = $newOptions }
                    Write-Host "  Updated site link: $($SiteLink.Name)" -ForegroundColor Cyan
                }
                catch {
                    Write-Error "Failed to update site link $($SiteLink.Name): $_"
                }
            }
        }
    }

    if ($EnableReplicationConnections -and $ConnectionsNeedChange) {
        $BackupData += "REPLICATION CONNECTIONS (before changes):"
        $BackupData += ($ConnectionsNeedChange | Select-Object Name, DistinguishedName, Options, OptionsHex | Format-List | Out-String)

        foreach ($Connection in $ConnectionsNeedChange) {
            $newOptions = $Connection.Options -bor $CONN_USE_NOTIFY
            if ($PSCmdlet.ShouldProcess($Connection.Name, "Set options from 0x$($Connection.Options.ToString('X')) to 0x$($newOptions.ToString('X'))")) {
                try {
                    Set-ADReplicationConnection -Identity $Connection.DistinguishedName -Replace @{'options' = $newOptions }
                    Write-Host "  Updated connection: $($Connection.Name)" -ForegroundColor Cyan
                }
                catch {
                    Write-Error "Failed to update connection $($Connection.Name): $_"
                }
            }
        }
    }

    # Save backup
    if ($BackupData.Count -gt 2) {
        $BackupData | Out-File -FilePath $BackupPath -Encoding UTF8 -Force
        Write-Host "Backup saved to: $BackupPath" -ForegroundColor Yellow
    }
}

#endregion
