# Add to Enable-UseNotifyReport.ps1
[CmdletBinding(SupportsShouldProcess = $true)]
param (
    [switch]$SetSiteLinks = $false,
    [switch]$SetReplicationConnections = $false,
    [switch]$Force
)

<#
    .SYNOPSIS
    This function Enables the Use_Notify option on Site Links, Replication Connections, or both.

    .EXAMPLE
    .\Enable-UseNotifyReport.ps1 -SetSiteLinks
    .\Enable-UseNotifyReport.ps1 -SetReplicationConnections
    .\Enable-UseNotifyReport.ps1 -SetSiteLinks -SetReplicationConnections
#>


if ($SetSiteLinks -or $SetReplicationConnections) {

    Import-Module ActiveDirectory

    # Create backup before making changes
    if ($SetSiteLinks -or $SetReplicationConnections) {
        $BackupPath = "$env:USERPROFILE\desktop\$(Get-Date -Format ddMMMyyyy_HHmm)_UseNotify_Backup.txt"
        $BackupData = @()

        if ($SetSiteLinks) {
            $BackupData += "`nSITE LINKS BACKUP:"
            $BackupData += (Get-ADReplicationSiteLink -Filter * -Properties options |
                Select-Object Name, DistinguishedName, options | Format-List | Out-String)
        }

        if ($SetReplicationConnections) {
            $BackupData += "`nREPLICATION CONNECTIONS BACKUP:"
            $BackupData += (Get-ADReplicationConnection -Filter * -Properties options |
                Select-Object Name, DistinguishedName, options | Format-List | Out-String)
        }

        Write-Verbose "Creating backup at $BackupPath"
        $BackupData | Out-File $BackupPath -Force
    }

    $VerbosePreference = "Continue"

    if ($SetSiteLinks) {
        $SiteLinks = Get-ADReplicationSiteLink -Filter * -Properties options | Select-Object *, @{n = 'NotifyEnabled'; e = { 1 -eq ($_.options -band 1) } }
        $SiteLinksToEnable = $SiteLinks | Where-Object NotifyEnabled -eq $false

        $SiteLinksToEnable | ForEach-Object {
            [int]$RecommendedOptionsValue = $_.options -bor 1
            if ($PSCmdlet.ShouldProcess($_.DistinguishedName, "Set options to $RecommendedOptionsValue")) {
                Write-Verbose "Setting $($_.DistinguishedName) to $RecommendedOptionsValue "
                try {
                    Set-ADReplicationSiteLink -Identity $_.DistinguishedName -Replace @{'options' = $RecommendedOptionsValue }
                }
                catch {
                    Write-Error "Failed to update site link $($_.DistinguishedName): $_"
                }
            }
        }
    }
    else { Write-Verbose "SetSiteLinks is false. Skipping Site Links" }

    if ($SetReplicationConnections) {
        $ADReplicationConnectionFilter1 = @(
            'Name'
            @{n = 'FromServer'    ; e = { ($_.ReplicateFromDirectoryServer -split ',')[1] -replace 'CN=', '' } }
            @{n = 'ToServer'      ; e = { ($_.ReplicateToDirectoryServer -split ',')[0] -replace 'CN=', '' } }
            'AutoGenerated'
            @{n = 'NotifyEnabled' ; e = { 8 -eq ($_.options -band 8) } }
            @{n = 'ParentSite'    ; e = { ($_.DistinguishedName -split ',')[4] -replace 'CN=', '' } }
            'DistinguishedName'
            'Options'
        )
        $ADReplicationConnectionFilter2 = @(
            '*'
            @{n   = 'RecommendedOptionsValue'
                e = {
                    if ($_.NotifyEnabled -or $_.AutoGenerated) { "NoChange" }
                    else { $_.options -bor 8 }
                }
            }
        )
        $ReplicationConnections = Get-ADReplicationConnection -Filter * -Properties options | Select-Object $ADReplicationConnectionFilter1 | Select-Object $ADReplicationConnectionFilter2

        $ReplicationConnections | Where-Object RecommendedOptionsValue -ne "NoChange" | ForEach-Object {
            [int]$RecommendedOptionsValue = $_.RecommendedOptionsValue
            if ($PSCmdlet.ShouldProcess($_.DistinguishedName, "Set options to $RecommendedOptionsValue")) {
                Write-Verbose "Setting $($_.DistinguishedName) to $RecommendedOptionsValue"
                try {
                    Set-ADReplicationConnection -Identity $_.DistinguishedName -Replace @{'options' = $RecommendedOptionsValue }
                }
                catch {
                    Write-Error "Failed to update replication connection $($_.DistinguishedName): $_"
                }
            }
        }
    }
    else { Write-Verbose "SetReplicationConnections is false. Skipping Replication Connections" }
}
else { Write-Warning "No Action Taken. Use the SetSiteLinks or SetReplicationConnections parameter or both." }
