[CmdletBinding()]
param (
    [ValidateNotNullOrEmpty()]
    [string]$ReportPath = "$env:USERPROFILE\desktop\$(Get-Date -Format 'ddMMMyyyy')_UseNotifyReport.txt"
)

<#
    .SYNOPSIS
    Evaluates AD replication topology to identify where the Use_Notify feature isn't enabled.
    Reports findings to the desktop or other path specified by -ReportPath

    .EXAMPLE
    .\Get-UseNotifyReport.ps1
    .\Get-UseNotifyReport.ps1 -ReportPath C:\Reports\12Jan2024_UseNotifyReport.txt
#>

Import-Module ActiveDirectory
$SiteLinks = Get-ADReplicationSiteLink -Filter * -Properties options | select *, @{n = 'NotifyEnabled'; e = { 1 -eq ($_.options -band 1) } }

$ADReplicationConnectionFilter1 = @(
    'Name'
    @{n = 'FromServer'    ; e = { ($_.ReplicateFromDirectoryServer -split ',')[1] -replace 'CN=', '' } }
    @{n = 'ToServer'      ; e = { ($_.ReplicateToDirectoryServer -split ',')[0] -replace 'CN=', '' } }
    'AutoGenerated'
    @{n = 'NotifyEnabled' ; e = { 8 -eq ($_.options -band 8) } }
    @{n = 'ParentSite'    ; e = { ($_.DistinguishedName -split ',')[4] -replace 'CN=', '' } }
    #'DistinguishedName'
    'Options'
)
$ADReplicationConnectionFilter2 = @(
    '*'
    @{n   = 'RecommendedOptionsValue'
        e = {
            if ($_.NotifyEnabled -or $_.AutoGenerated) { "NoChange" }
            else { $_.options -bor 8 }
        }
    }
)

$ReplicationConnections = Get-ADReplicationConnection -Filter * -Properties options | select $ADReplicationConnectionFilter1 | select $ADReplicationConnectionFilter2

$Output = @()

$Output += "`n"
$Output += ("`n" + ($SiteLinks | Where-Object NotifyEnabled).count + " SITE LINKS have Use_Notify configured (1st options bit):")
$Output += ($SiteLinks | Where-Object NotifyEnabled | Select-Object Name, DistinguishedName | Format-Table)
$Output += ("`n" + ($SiteLinks | Where-Object { -not $_.NotifyEnabled }).count + " SITE LINKS do not have Use_Notify configured (1st options bit): `n")
$Output += (($SiteLinks | Where-Object { $_.NotifyEnabled -ne $true }) | select Name, DistinguishedName | Format-Table)

$Output += ("`nWhere AutoGenerated is false, REPLICATION CONNECTIONS must have Use_Notify explicity set (4th options bit).")
$Output += ("`n" + ($ReplicationConnections | Where-Object { $_.RecommendedOptionsValue -eq 'NoChange' }).count + " REPLICATION CONNECTIONS are either inheriting the SITE LINK behavior or are already configured for Use_Notify and therefore require no change: `n")
$Output += ($ReplicationConnections | Where-Object { $_.RecommendedOptionsValue -eq 'NoChange' } | Format-Table)
$Output += ("`n" + ($ReplicationConnections | Where-Object { $_.RecommendedOptionsValue -ne 'NoChange' }).count + " REPLICATION CONNECTIONS are not AutoGenerated, but do not have Use_Notify configured. You may wish to change the Options attribute: `n")
$Output += ($ReplicationConnections | Where-Object { $_.RecommendedOptionsValue -ne 'NoChange' } | Format-Table)

New-Item $ReportPath -Force
$Output | Out-File $ReportPath -Force