<#
.SYNOPSIS
    Evaluates and optionally enables the Use_Notify option on AD Site Links and Replication Connections.

.DESCRIPTION
    This tool analyzes Active Directory replication topology to identify where the Use_Notify
    feature isn't enabled, and can optionally enable it.

    Use_Notify enables change notification between domain controllers, reducing replication latency
    from the default 15-minute schedule to near-immediate replication.

    Site Link Options (bit flags):
        0x1 (bit 0) - USE_NOTIFY: Enables change notification for the site link

    Replication Connection Options (bit flags):
        0x1 (bit 0) - IS_GENERATED: Connection was auto-generated by KCC
        0x2 (bit 1) - USE_NOTIFY: Enables change notification for the connection

    Reference: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/

.PARAMETER ReportOnly
    Generate a report without making any changes. This is the default behavior.

.PARAMETER EnableSiteLinks
    Enable Use_Notify on site links that don't have it configured.

.PARAMETER EnableReplicationConnections
    Enable Use_Notify on manually-created replication connections that don't have it configured.
    Note: Auto-generated connections inherit behavior from site links.

.PARAMETER ReportPath
    Path to save the report file. Defaults to desktop.

.EXAMPLE
    .\Set-UseNotifyReplication.ps1
    Generates a report of current Use_Notify status without making changes.

.EXAMPLE
    .\Set-UseNotifyReplication.ps1 -EnableSiteLinks -WhatIf
    Shows what site links would be modified without making changes.

.EXAMPLE
    .\Set-UseNotifyReplication.ps1 -EnableSiteLinks -EnableReplicationConnections
    Enables Use_Notify on both site links and manual replication connections.

.LINK
    https://github.com/Mike-Crowley/Public-Scripts

.NOTES
    Author: Mike Crowley
    Requires: ActiveDirectory module
#>

#Requires -Modules ActiveDirectory

[CmdletBinding(SupportsShouldProcess = $true, DefaultParameterSetName = 'Report')]
param (
    [Parameter(ParameterSetName = 'Report')]
    [switch]$ReportOnly,

    [Parameter(ParameterSetName = 'Enable')]
    [switch]$EnableSiteLinks,

    [Parameter(ParameterSetName = 'Enable')]
    [switch]$EnableReplicationConnections,

    [ValidateNotNullOrEmpty()]
    [string]$ReportPath = "$env:USERPROFILE\Desktop\$(Get-Date -Format 'yyyyMMdd_HHmmss')_UseNotifyReport.txt"
)

# Bit flag constants
$SITELINK_USE_NOTIFY = 0x1          # Bit 0 for site links
$CONN_IS_GENERATED = 0x1            # Bit 0 for connections (auto-generated)
$CONN_USE_NOTIFY = 0x2              # Bit 1 for connections (use notify)

#region Helper Functions

function Get-SiteLinkStatus {
    [CmdletBinding()]
    param()

    Get-ADReplicationSiteLink -Filter * -Properties options | ForEach-Object {
        $options = if ($null -eq $_.options) { 0 } else { [int]$_.options }
        [PSCustomObject]@{
            Name              = $_.Name
            DistinguishedName = $_.DistinguishedName
            Options           = $options
            OptionsHex        = '0x{0:X}' -f $options
            NotifyEnabled     = ($options -band $SITELINK_USE_NOTIFY) -eq $SITELINK_USE_NOTIFY
        }
    }
}

function Get-ReplicationConnectionStatus {
    [CmdletBinding()]
    param()

    Get-ADReplicationConnection -Filter * -Properties options | ForEach-Object {
        $options = if ($null -eq $_.options) { 0 } else { [int]$_.options }
        $isGenerated = ($options -band $CONN_IS_GENERATED) -eq $CONN_IS_GENERATED
        $notifyEnabled = ($options -band $CONN_USE_NOTIFY) -eq $CONN_USE_NOTIFY

        [PSCustomObject]@{
            Name              = $_.Name
            FromServer        = ($_.ReplicateFromDirectoryServer -split ',')[1] -replace 'CN=', ''
            ToServer          = ($_.ReplicateToDirectoryServer -split ',')[0] -replace 'CN=', ''
            ParentSite        = ($_.DistinguishedName -split ',')[4] -replace 'CN=', ''
            DistinguishedName = $_.DistinguishedName
            Options           = $options
            OptionsHex        = '0x{0:X}' -f $options
            AutoGenerated     = $isGenerated
            NotifyEnabled     = $notifyEnabled
            NeedsChange       = (-not $isGenerated) -and (-not $notifyEnabled)
        }
    }
}

#endregion

#region Main Logic

Write-Verbose "Retrieving site link information..."
$SiteLinks = Get-SiteLinkStatus

Write-Verbose "Retrieving replication connection information..."
$ReplicationConnections = Get-ReplicationConnectionStatus

$SiteLinksEnabled = $SiteLinks | Where-Object { $_.NotifyEnabled }
$SiteLinksDisabled = $SiteLinks | Where-Object { -not $_.NotifyEnabled }
$ConnectionsOK = $ReplicationConnections | Where-Object { -not $_.NeedsChange }
$ConnectionsNeedChange = $ReplicationConnections | Where-Object { $_.NeedsChange }

# Build report
$Report = @()
$Report += "=" * 80
$Report += "USE_NOTIFY REPLICATION REPORT"
$Report += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$Report += "=" * 80
$Report += ""
$Report += "SITE LINKS"
$Report += "-" * 40
$Report += "$($SiteLinksEnabled.Count) site link(s) have Use_Notify ENABLED (bit 0 = 0x1):"
if ($SiteLinksEnabled) {
    $Report += ($SiteLinksEnabled | Select-Object Name, OptionsHex | Format-Table -AutoSize | Out-String).Trim()
}
$Report += ""
$Report += "$($SiteLinksDisabled.Count) site link(s) do NOT have Use_Notify enabled:"
if ($SiteLinksDisabled) {
    $Report += ($SiteLinksDisabled | Select-Object Name, OptionsHex, DistinguishedName | Format-Table -AutoSize | Out-String).Trim()
}
$Report += ""
$Report += "REPLICATION CONNECTIONS"
$Report += "-" * 40
$Report += "Note: Auto-generated connections (bit 0 = 0x1) inherit Use_Notify from site links."
$Report += "      Manual connections need Use_Notify explicitly set (bit 1 = 0x2)."
$Report += ""
$Report += "$($ConnectionsOK.Count) connection(s) are OK (auto-generated or already have Use_Notify):"
if ($ConnectionsOK) {
    $Report += ($ConnectionsOK | Select-Object Name, FromServer, ToServer, AutoGenerated, NotifyEnabled, OptionsHex | Format-Table -AutoSize | Out-String).Trim()
}
$Report += ""
$Report += "$($ConnectionsNeedChange.Count) manual connection(s) need Use_Notify enabled:"
if ($ConnectionsNeedChange) {
    $Report += ($ConnectionsNeedChange | Select-Object Name, FromServer, ToServer, OptionsHex, DistinguishedName | Format-Table -AutoSize | Out-String).Trim()
}

# Save report
$Report | Out-File -FilePath $ReportPath -Encoding UTF8 -Force
Write-Host "Report saved to: $ReportPath" -ForegroundColor Green

# If in enable mode, make changes
if ($EnableSiteLinks -or $EnableReplicationConnections) {

    # Create backup before making changes
    $BackupPath = $ReportPath -replace '\.txt$', '_Backup.txt'
    $BackupData = @()
    $BackupData += "BACKUP CREATED: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $BackupData += ""

    if ($EnableSiteLinks -and $SiteLinksDisabled) {
        $BackupData += "SITE LINKS (before changes):"
        $BackupData += ($SiteLinksDisabled | Select-Object Name, DistinguishedName, Options, OptionsHex | Format-List | Out-String)

        foreach ($SiteLink in $SiteLinksDisabled) {
            $newOptions = $SiteLink.Options -bor $SITELINK_USE_NOTIFY
            if ($PSCmdlet.ShouldProcess($SiteLink.Name, "Set options from 0x$($SiteLink.Options.ToString('X')) to 0x$($newOptions.ToString('X'))")) {
                try {
                    Set-ADReplicationSiteLink -Identity $SiteLink.DistinguishedName -Replace @{'options' = $newOptions }
                    Write-Host "  Updated site link: $($SiteLink.Name)" -ForegroundColor Cyan
                }
                catch {
                    Write-Error "Failed to update site link $($SiteLink.Name): $_"
                }
            }
        }
    }

    if ($EnableReplicationConnections -and $ConnectionsNeedChange) {
        $BackupData += "REPLICATION CONNECTIONS (before changes):"
        $BackupData += ($ConnectionsNeedChange | Select-Object Name, DistinguishedName, Options, OptionsHex | Format-List | Out-String)

        foreach ($Connection in $ConnectionsNeedChange) {
            $newOptions = $Connection.Options -bor $CONN_USE_NOTIFY
            if ($PSCmdlet.ShouldProcess($Connection.Name, "Set options from 0x$($Connection.Options.ToString('X')) to 0x$($newOptions.ToString('X'))")) {
                try {
                    Set-ADReplicationConnection -Identity $Connection.DistinguishedName -Replace @{'options' = $newOptions }
                    Write-Host "  Updated connection: $($Connection.Name)" -ForegroundColor Cyan
                }
                catch {
                    Write-Error "Failed to update connection $($Connection.Name): $_"
                }
            }
        }
    }

    # Save backup
    if ($BackupData.Count -gt 2) {
        $BackupData | Out-File -FilePath $BackupPath -Encoding UTF8 -Force
        Write-Host "Backup saved to: $BackupPath" -ForegroundColor Yellow
    }
}

#endregion
